// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifiwmnwnlmtvleebitcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmaXdtbndubG10dmxlZWJpdGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMwNzgwNjMsImV4cCI6MjA5ODY1NDA2M30.MUoqrvnKYgJZqi2jp6w2dVO2cNjRijUEkBjkkgm50hM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});